### ISSUE TITLE
Shoot confetti and set custom origin inside of card element

### ISSUE THREAD

**Issue by julianwitzel** [catdad/canvas-confetti#197] opened 2023-06-07 18:23 UTC
Thank you for creating this amazing little tool!

We are trying to use the confetti canon inside of a card box. The origin should be the right border of this element. And also the top value of the origin should be relative to the box.

This way you would be able to set the origin to 30% of the height and 0% from the right.

I hope it is clear what I mean. Maybe there is also an easy way to achieve this?

**Comment by catdad** [comment] 2023-09-08 03:59
This is a duplicate of #129. Essentially, you are asking that the confetti be fired from an arbitrary location that you have picked, that is not generalized to other users. You can already make the origin whatever you want by doing the necessary math.

**Closed by catdad** 2023-09-08 03:59 UTC
