### ISSUE TITLE
provide origin as an HTMLElement

### ISSUE THREAD

**Issue by G-Bro** [catdad/canvas-confetti#147] opened 2021-03-26 09:21 UTC
It would be handy to be able to provide an element for the confetti's origin point

Currently I am doing this to convert an element into an origin to be passed through to the confetti function

```js
const rect = element.getBoundingClientRect();
options.origin = {
  x: (rect.x + (rect.width / 2)) / window.screen.width,
  y: ((rect.y + (rect.height / 2)) / window.screen.height),
};
```

**Comment by BobbyTable** [comment] 2021-04-08 13:36
Heres a snippet that lets your create points on an element to "fire from"
```
const el = document.getElementById(elemId);
const rect = el.getBoundingClientRect();

const buildPos = (factorX, factorY) => ({
	x: (rect.left - ((rect.left - rect.right) * factorX)) / window.innerWidth,
	y: (rect.top - ((rect.top - rect.bottom) * factorY)) / window.innerHeight
})

// Usage (creation of points)
const middleRight = buildPos(1, .5);
const topCenter = buildPos(.5, 0);
```

**Comment by catdad** [comment] 2021-04-15 21:40
This is a duplicate of #129. Seeing as there is ambiguity in what "from an element" means (e.g. is it from the center, one side or another, a corner, is it different for every user), and it is trivial to implement your own use case using the existing options, I am going to close this.

**Closed by catdad** 2021-04-15 21:40 UTC
Labels: duplicate
